name: Python Doctest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Run doctest
        run: |
              python -m doctest -v source/Constants.py
              python -m doctest -v source/Controller.py
              python -m doctest -v source/Main.py
              python -m doctest -v source/PoseDetection.py
